//
//  CREADO POR ALEJANDRO VICENTE Y ALBERTO MARCOS
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Agenda.java
//  @ Date : 23/05/2018
//  @ Author : 
//
//



package DiagramaDeClases;


public class Agenda {
	public Object categoria;
	public Object esFavorita;
	public void new() {
	
	}
	
	public void marcarFavorita() {
	
	}
	
	public void anadirUsuarios() {
	
	}
	
	public void configurarAgenda() {
	
	}
	
	public void listarContactos() {
	
	}
	
	public void eliminarUsuario() {
	
	}
	
	public void destroy() {
	
	}
}
