//
//  CREADO POR ALEJANDRO VICENTE Y ALBERTO MARCOS
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Conversacion.java
//  @ Date : 23/05/2018
//  @ Author : 
//
//



package Diagrama de clases;


public class Conversacion {
	public Object fechaInicio;
	public void new() {
	
	}
	
	public void eliminarMensaje() {
	
	}
	
	public void destroy() {
	
	}
}
