//
//  CREADO POR ALEJANDRO VICENTE Y ALBERTO MARCOS
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Individual.java
//  @ Date : 23/05/2018
//  @ Author : 
//
//



package Diagrama de clases;


public class Individual extends Conversacion {
	public void iniciarChat() {
	
	}
}
