//
//  CREADO POR ALEJANDRO VICENTE Y ALBERTO MARCOS
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Mensaje.java
//  @ Date : 23/05/2018
//  @ Author : 
//
//



package Diagrama de clases;


public class Mensaje {
	public Object usuarioEmisor;
	public Object conversacion;
	public Object fecha;
	public Object hora;
	public Object cuerpo;
	public void new() {
	
	}
	
	public void destroy() {
	
	}
}
