//
//  CREADO POR ALEJANDRO VICENTE Y ALBERTO MARCOS
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Notificacion.java
//  @ Date : 23/05/2018
//  @ Author : 
//
//



package Diagrama de clases;


public class Notificacion {
	public Object titulo;
	public Object cuerpo;
	public TipoNotificacion tipo;
	public void new() {
	
	}
	
	public void destroy() {
	
	}
}
