//
//  CREADO POR ALEJANDRO VICENTE Y ALBERTO MARCOS
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Perfil.java
//  @ Date : 23/05/2018
//  @ Author : 
//
//



package Diagrama de clases;


public class Perfil {
	public Object alias;
	public Object estado;
	public Object imagen;
	public Object descripcion;
	public void new() {
	
	}
	
	public void verPerfil() {
	
	}
	
	public void destroy() {
	
	}
}
