//
//  CREADO POR ALEJANDRO VICENTE Y ALBERTO MARCOS
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Usuario.java
//  @ Date : 23/05/2018
//  @ Author : 
//
//



package DiagramaDeClases;

public class Usuario {
	public Object idUsuario;
	public Object nombre;
	public Object apellidos;
	public Object correoElectronico;
	public Object contrasena;
	public void new() {
	
	}
	
	public void loguearse() {
	
	}
	
	public void recordarContrasena() {
	
	}
	
	public void destroy() {
	
	}
}
