//
//  CREADO POR ALEJANDRO VICENTE Y ALBERTO MARCOS
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Agenda.java
//  @ Date : 23/05/2018
//  @ Author : 
//
//




public class Agenda implements IContactosAgenda, INotificable, INotificable, INotificable {
	public Integer idAgenda;
	public String categoria;
	public String nombreAgenda;
	public Boolean esFavorita;
	public void new() {
	
	}
	
	public String getIdAgenda() {
	
	}
	
	public String getNombreAgenda() {
	
	}
	
	public Boolean esFavorita() {
	
	}
	
	public void destroy() {
	
	}
	
	public void buscarContacto(String nombreUsuario);
	
	public Integer numeroContactos();
	
	public void borrarContacto(Integer idUsuario);
	
	public void anadirContacto(Usuario usuario);
	
	public ArrayList<<Usuarios>> listarContacto();
	
	public void mostrarNotificacion();
	
	public void borrarNotificacion();
	
	public void crearNotificacion();
	
	public void mostrarNotificacion();
	
	public void borrarNotificacion();
	
	public void crearNotificacion();
	
	public void mostrarNotificacion();
	
	public void borrarNotificacion();
	
	public void crearNotificacion();
}
