package DesignModel;//
//  CREADO POR ALEJANDRO VICENTE Y ALBERTO MARCOS
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : BDPerfil.java
//  @ Date : 23/05/2018
//  @ Author : 
//
//




public class BDPerfil implements IDataBase {
	public void INSERT();
	public void UPDATE();
	public void DELETE();
	public void SELECT();
}
