package DesignModel;//
//  CREADO POR ALEJANDRO VICENTE Y ALBERTO MARCOS
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ConcreteProduct.java
//  @ Date : 23/05/2018
//  @ Author : 
//
//


import DesignModel.Product;

public class ConcreteProduct extends Product {

}
