//
//  CREADO POR ALEJANDRO VICENTE Y ALBERTO MARCOS
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ControladorAgenda.java
//  @ Date : 23/05/2018
//  @ Author : 
//
//




public class ControladorAgenda {
	public void añadirAgenda() {
	
	}
	
	public void modificarAgenda() {
	
	}
	
	public void borrarAgenda() {
	
	}
	
	public void marcarFavorita() {
	
	}
}
