package DesignModel;//
//  CREADO POR ALEJANDRO VICENTE Y ALBERTO MARCOS
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ControladorConversacion.java
//  @ Date : 23/05/2018
//  @ Author : 
//
//




public class ControladorConversacion {
	public void anadirConversacion() {
	
	}
	
	public void modificarConversacion() {
	
	}
	
	public void borrarConversacion() {
	
	}
}
