//
//  CREADO POR ALEJANDRO VICENTE Y ALBERTO MARCOS
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ControladorPerfil.java
//  @ Date : 23/05/2018
//  @ Author : 
//
//




public class ControladorPerfil {
	public void añadirPerfil() {
	
	}
	
	public void modificarPerfil() {
	
	}
	
	public void borrarPerfil() {
	
	}
	
	public void verPerfil() {
	
	}
}
