//
//  CREADO POR ALEJANDRO VICENTE Y ALBERTO MARCOS
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ControladorUsuario.java
//  @ Date : 23/05/2018
//  @ Author : 
//
//




public class ControladorUsuario {
	public void añadirUsuario() {
	
	}
	
	public void modificarUsuario() {
	
	}
	
	public void borrarUsuario() {
	
	}
	
	public void recordarContraseña() {
	
	}
}
