//
//  CREADO POR ALEJANDRO VICENTE Y ALBERTO MARCOS
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GUINotificacion.java
//  @ Date : 23/05/2018
//  @ Author : 
//
//




public class GUINotificacion {
}
