package DesignModel;//
//  CREADO POR ALEJANDRO VICENTE Y ALBERTO MARCOS
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IConversacionFactoryMethod.java
//  @ Date : 23/05/2018
//  @ Author : 
//
//


import DiagramaDeClases.Conversacion;
import DiagramaDeClases.Mensaje;
import DiagramaDeClases.Usuario;

import java.util.ArrayList;

public interface IConversacionFactoryMethod {
	public Conversacion iniciarConversacion(String fechaInicio, Mensaje mensaje, ArrayList<Usuario> usuarios);
}
