//
//  CREADO POR ALEJANDRO VICENTE Y ALBERTO MARCOS
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IContactosAgenda.java
//  @ Date : 23/05/2018
//  @ Author : 
//
//




public interface IContactosAgenda {
	public void buscarContacto(String nombreUsuario);
	public Integer numeroContactos();
	public void borrarContacto(Integer idUsuario);
	public void añadirContacto(Usuario usuario);
	public ArrayList<<Usuarios>> listarContacto();
}
