//
//  CREADO POR ALEJANDRO VICENTE Y ALBERTO MARCOS
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : INotificable.java
//  @ Date : 23/05/2018
//  @ Author : 
//
//




public interface INotificable {
	public void mostrarNotificacion();
	public void borrarNotificacion();
	public void crearNotificacion();
}
