//
//  CREADO POR ALEJANDRO VICENTE Y ALBERTO MARCOS
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Mensaje.java
//  @ Date : 23/05/2018
//  @ Author : 
//
//




public class Mensaje implements INotificable {
	private Object idMensaje;
	private Integer usuarioEmisor;
	private Integer conversacion;
	private String fecha;
	private String hora;
	private String cuerpo;
	public void new() {
	
	}
	
	public Integer getUsuarioEmisor() {
	
	}
	
	public Integer getConversacion() {
	
	}
	
	public String getFecha() {
	
	}
	
	public String getHora() {
	
	}
	
	public String getCuerpo() {
	
	}
	
	public void destroy() {
	
	}
	
	public void mostrarNotificacion();
	
	public void borrarNotificacion();
	
	public void crearNotificacion();
}
