//
//  CREADO POR ALEJANDRO VICENTE Y ALBERTO MARCOS
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Notificacon.java
//  @ Date : 23/05/2018
//  @ Author : 
//
//




public class Notificacon {
	private String titulo;
	private String cuerpo;
	private el.Diagrama de clases.TipoNotificacion tipo; CREAR ENUM
	public void new() {
	
	}
	
	public String getTitulo() {
	
	}
	
	public String getCuerpo() {
	
	}
	
	public void setTitulo(String titulo) {
	
	}
	
	public void setCuerpo(String cuerpo) {
	
	}
	
	public void destroy() {
	
	}
}
