//
//  CREADO POR ALEJANDRO VICENTE Y ALBERTO MARCOS
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Perfil.java
//  @ Date : 23/05/2018
//  @ Author : 
//
//




public class Perfil {
	private String alias;
	private String estado;
	private String imagen;
	private String descripcion;
	public void new() {
	
	}
	
	public String getAlias() {
	
	}
	
	public String getEstado() {
	
	}
	
	public String getImagen() {
	
	}
	
	public void setAlias(String alias) {
	
	}
	
	public void setEstado(String estado) {
	
	}
	
	public void setImagen(String imagen) {
	
	}
	
	public void destroy() {
	
	}
}
