//
//  CREADO POR ALEJANDRO VICENTE Y ALBERTO MARCOS
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Usuario.java
//  @ Date : 23/05/2018
//  @ Author : 
//
//




private class Usuario implements IMensajeable {
	private Integer idUsuario;
	private String nombre;
	private String apellidos;
	private String correoElectronico;
	private String contraseña;
	public void new() {
	
	}
	
	public void accederSistema() {
	
	}
	
	public Integer getIdUsuario() {
	
	}
	
	public String getNombre() {
	
	}
	
	public String getApellidos() {
	
	}
	
	public String getCorreoElectronico() {
	
	}
	
	public String getContraseña() {
	
	}
	
	public void setIdUsuario(Integer idUsuario) {
	
	}
	
	public void setNombre(String nombre) {
	
	}
	
	public void setApellidos(String apellidos) {
	
	}
	
	public void setContraseña(String contraseña) {
	
	}
	
	public void destroy() {
	
	}
	
	public ArrayList <<Mensaje>> listarMensajes();
	
	public void borrarMensaj(Integer idMensaje);
	
	public Mensaje getMensaje();
	
	public void enviarMensaje(Mensaje mensaje);
}
