//
//  CREADO POR ALEJANDRO VICENTE Y ALBERTO MARCOS
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Volatil.java
//  @ Date : 23/05/2018
//  @ Author : 
//
//




public class Volatil extends Mensaje {
	private Integer tiempoDeVida;
	public void new() {
	
	}
	
	public Integer getTiempoDeVida() {
	
	}
	
	public void destroy() {
	
	}
	
	public void mostrarNotificacion();
	
	public void borrarNotificacion();
	
	public void crearNotificacion();
}
